-- Supabase Database Schema for Nolads Engineering
-- Run this SQL in your Supabase SQL Editor to create all necessary tables

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table (extends Supabase auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    avatar_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Services table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    short_description TEXT,
    price_range VARCHAR(100),
    category VARCHAR(100),
    image_url TEXT,
    features TEXT, -- JSON string
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(12,2),
    category VARCHAR(100),
    image_url TEXT,
    images TEXT, -- JSON array of image URLs
    specifications TEXT, -- JSON string
    stock_quantity INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Quotes table
CREATE TABLE IF NOT EXISTS public.quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    service_id BIGINT REFERENCES public.services(id),
    project_name VARCHAR(255) NOT NULL,
    description TEXT,
    requirements TEXT, -- JSON string
    budget_range VARCHAR(100),
    timeline VARCHAR(100),
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'approved', 'rejected')),
    estimated_cost DECIMAL(12,2),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Contact Messages table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    subject VARCHAR(255),
    message TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'replied')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    position VARCHAR(255),
    content TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Images table for file management
CREATE TABLE IF NOT EXISTS public.images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size INTEGER NOT NULL,
    path TEXT NOT NULL,
    url TEXT NOT NULL,
    alt_text TEXT,
    entity_type VARCHAR(50) CHECK (entity_type IN ('user', 'service', 'product', 'quote')),
    entity_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Blog Posts table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    featured_image TEXT,
    category VARCHAR(100),
    tags TEXT[], -- Array of tags
    author_id BIGINT REFERENCES public.users(id),
    author_name VARCHAR(255),
    author_email VARCHAR(255),
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    published_at TIMESTAMP WITH TIME ZONE,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    meta_title VARCHAR(255),
    meta_description TEXT
);

-- Blog Categories table
CREATE TABLE IF NOT EXISTS public.blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Blog Comments table
CREATE TABLE IF NOT EXISTS public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id),
    author_name VARCHAR(255) NOT NULL,
    author_email VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'spam')),
    is_approved BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add missing columns to existing tables (safe migration for re-runs)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS price_range VARCHAR(100);
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS features TEXT;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS price DECIMAL(10,2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sku VARCHAR(100);
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS service_id BIGINT REFERENCES public.services(id);
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.contact_messages ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'unread';
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'draft';
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS featured_image TEXT;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS author_id BIGINT;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS author_name VARCHAR(255);
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS author_email VARCHAR(255);
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255);
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE public.blog_categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.blog_comments ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE public.blog_comments ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT false;

-- Create updated_at triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create blog post management functions
CREATE OR REPLACE FUNCTION create_blog_post(
    post_data JSONB,
    tag_ids JSONB DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
    new_post_id BIGINT;
    result JSONB;
    tags_array TEXT[];
BEGIN
    -- Convert tag_ids JSONB to TEXT[] if provided
    IF tag_ids IS NOT NULL THEN
        SELECT ARRAY(SELECT jsonb_array_elements_text(tag_ids)) INTO tags_array;
    END IF;
    
    -- Insert the blog post
    INSERT INTO public.blog_posts (
        title,
        slug,
        content,
        excerpt,
        featured_image,
        category,
        tags,
        author_id,
        status,
        published_at,
        meta_title,
        meta_description
    ) VALUES (
        (post_data->>'title')::VARCHAR(255),
        (post_data->>'slug')::VARCHAR(255),
        (post_data->>'content')::TEXT,
        (post_data->>'excerpt')::TEXT,
        (post_data->>'featured_image')::TEXT,
        (post_data->>'category')::VARCHAR(100),
        COALESCE(tags_array, (post_data->'tags')::TEXT[]),
        (post_data->>'author_id')::BIGINT,
        COALESCE((post_data->>'status')::VARCHAR(20), 'draft'),
        CASE 
            WHEN (post_data->>'status')::VARCHAR(20) = 'published' THEN NOW()
            ELSE NULL
        END,
        (post_data->>'meta_title')::VARCHAR(255),
        (post_data->>'meta_description')::TEXT
    ) RETURNING id INTO new_post_id;
    
    -- Return the created post data
    SELECT to_jsonb(bp.*) INTO result
    FROM public.blog_posts bp
    WHERE bp.id = new_post_id;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_blog_post(
    post_id BIGINT,
    post_updates JSONB,
    tag_ids JSONB DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
    result JSONB;
    tags_array TEXT[];
BEGIN
    -- Convert tag_ids JSONB to TEXT[] if provided
    IF tag_ids IS NOT NULL THEN
        SELECT ARRAY(SELECT jsonb_array_elements_text(tag_ids)) INTO tags_array;
    END IF;
    
    -- Update the blog post
    UPDATE public.blog_posts SET
        title = COALESCE((post_updates->>'title')::VARCHAR(255), title),
        slug = COALESCE((post_updates->>'slug')::VARCHAR(255), slug),
        content = COALESCE((post_updates->>'content')::TEXT, content),
        excerpt = COALESCE((post_updates->>'excerpt')::TEXT, excerpt),
        featured_image = COALESCE((post_updates->>'featured_image')::TEXT, featured_image),
        category = COALESCE((post_updates->>'category')::VARCHAR(100), category),
        tags = COALESCE(tags_array, (post_updates->'tags')::TEXT[], tags),
        author_id = COALESCE((post_updates->>'author_id')::BIGINT, author_id),
        status = COALESCE((post_updates->>'status')::VARCHAR(20), status),
        published_at = CASE 
            WHEN (post_updates->>'status')::VARCHAR(20) = 'published' AND published_at IS NULL THEN NOW()
            WHEN (post_updates->>'status')::VARCHAR(20) != 'published' THEN NULL
            ELSE published_at
        END,
        meta_title = COALESCE((post_updates->>'meta_title')::VARCHAR(255), meta_title),
        meta_description = COALESCE((post_updates->>'meta_description')::TEXT, meta_description),
        updated_at = NOW()
    WHERE id = post_id;
    
    -- Return the updated post data
    SELECT to_jsonb(bp.*) INTO result
    FROM public.blog_posts bp
    WHERE bp.id = post_id;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers to relevant tables
DROP TRIGGER IF EXISTS update_users_updated_at ON public.users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_services_updated_at ON public.services;
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_products_updated_at ON public.products;
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_quotes_updated_at ON public.quotes;
CREATE TRIGGER update_quotes_updated_at BEFORE UPDATE ON public.quotes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_testimonials_updated_at ON public.testimonials;
CREATE TRIGGER update_testimonials_updated_at BEFORE UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_blog_posts_updated_at ON public.blog_posts;
CREATE TRIGGER update_blog_posts_updated_at BEFORE UPDATE ON public.blog_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_blog_categories_updated_at ON public.blog_categories;
CREATE TRIGGER update_blog_categories_updated_at BEFORE UPDATE ON public.blog_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_blog_comments_updated_at ON public.blog_comments;
CREATE TRIGGER update_blog_comments_updated_at BEFORE UPDATE ON public.blog_comments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_services_active ON public.services(is_active);
CREATE INDEX IF NOT EXISTS idx_services_category ON public.services(category);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_quotes_user_id ON public.quotes(user_id);
CREATE INDEX IF NOT EXISTS idx_quotes_service_id ON public.quotes(service_id);
CREATE INDEX IF NOT EXISTS idx_quotes_status ON public.quotes(status);
CREATE INDEX IF NOT EXISTS idx_contact_messages_status ON public.contact_messages(status);
CREATE INDEX IF NOT EXISTS idx_testimonials_active ON public.testimonials(is_active);
CREATE INDEX IF NOT EXISTS idx_testimonials_featured ON public.testimonials(is_featured);
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON public.blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON public.blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON public.blog_posts(published_at);
CREATE INDEX IF NOT EXISTS idx_blog_categories_slug ON public.blog_categories(slug);
CREATE INDEX IF NOT EXISTS idx_blog_comments_post_id ON public.blog_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_blog_comments_status ON public.blog_comments(status);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (idempotent: drop before re-create)

-- Services: Public read access, admin write access
DROP POLICY IF EXISTS "Public can view active services" ON public.services;
DROP POLICY IF EXISTS "Admins can manage services" ON public.services;
CREATE POLICY "Public can view active services" ON public.services FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage services" ON public.services FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Products: Public read access, admin write access
DROP POLICY IF EXISTS "Public can view active products" ON public.products;
DROP POLICY IF EXISTS "Admins can manage products" ON public.products;
CREATE POLICY "Public can view active products" ON public.products FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage products" ON public.products FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Quotes: Public can create quotes, admins can manage all
DROP POLICY IF EXISTS "Anyone can create quotes" ON public.quotes;
DROP POLICY IF EXISTS "Admins can view all quotes" ON public.quotes;
DROP POLICY IF EXISTS "Admins can manage quotes" ON public.quotes;
CREATE POLICY "Anyone can create quotes" ON public.quotes FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view all quotes" ON public.quotes FOR SELECT USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY "Admins can manage quotes" ON public.quotes FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Contact messages: Public can create, admins can read all
DROP POLICY IF EXISTS "Anyone can create contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Admins can view contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Admins can update contact messages" ON public.contact_messages;
CREATE POLICY "Anyone can create contact messages" ON public.contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view contact messages" ON public.contact_messages FOR SELECT USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY "Admins can update contact messages" ON public.contact_messages FOR UPDATE USING (auth.jwt() ->> 'role' = 'admin');

-- Testimonials: Public read access for active, admin full access
DROP POLICY IF EXISTS "Public can view active testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Admins can manage testimonials" ON public.testimonials;
CREATE POLICY "Public can view active testimonials" ON public.testimonials FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage testimonials" ON public.testimonials FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Users: admin-only access via RLS
-- NOTE: public.users.id is BIGINT (identity), not a UUID.
-- The auth.users table stores UUIDs. To link them, store the auth UUID in a separate column
-- (e.g. auth_id UUID UNIQUE) and compare auth.uid() against that column instead.
-- For now, only admin role can manage user rows directly; individual login is managed via auth.users.
DROP POLICY IF EXISTS "Users can view own profile" ON public.users;
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
DROP POLICY IF EXISTS "Admins can manage users" ON public.users;
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY "Admins can manage users" ON public.users FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Blog posts: Public read access for published, admin full access
DROP POLICY IF EXISTS "Public can view published blog posts" ON public.blog_posts;
DROP POLICY IF EXISTS "Admins can manage blog posts" ON public.blog_posts;
CREATE POLICY "Public can view published blog posts" ON public.blog_posts FOR SELECT USING (status = 'published');
CREATE POLICY "Admins can manage blog posts" ON public.blog_posts FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Blog categories: Public read access, admin full access
DROP POLICY IF EXISTS "Public can view active blog categories" ON public.blog_categories;
DROP POLICY IF EXISTS "Admins can manage blog categories" ON public.blog_categories;
CREATE POLICY "Public can view active blog categories" ON public.blog_categories FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage blog categories" ON public.blog_categories FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Blog comments: Authenticated users can create, public can view approved, admins can manage
DROP POLICY IF EXISTS "Public can view approved blog comments" ON public.blog_comments;
DROP POLICY IF EXISTS "Authenticated users can create blog comments" ON public.blog_comments;
DROP POLICY IF EXISTS "Admins can manage blog comments" ON public.blog_comments;
CREATE POLICY "Public can view approved blog comments" ON public.blog_comments FOR SELECT USING (is_approved = true);
CREATE POLICY "Authenticated users can create blog comments" ON public.blog_comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage blog comments" ON public.blog_comments FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Images: Public read access, authenticated users can upload
DROP POLICY IF EXISTS "Public can view images" ON public.images;
DROP POLICY IF EXISTS "Authenticated users can upload images" ON public.images;
DROP POLICY IF EXISTS "Users can manage own images" ON public.images;
CREATE POLICY "Public can view images" ON public.images FOR SELECT USING (true);
CREATE POLICY "Authenticated users can upload images" ON public.images FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can manage own images" ON public.images FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- Insert sample data

-- Sample Services
INSERT INTO public.services (name, description, short_description, category, is_active) VALUES
('Electrical Design & Engineering', 'Complete electrical system design and engineering services for industrial applications', 'Professional electrical design services', 'Design', true),
('Power System Installation', 'Installation of power distribution systems, transformers, and electrical infrastructure', 'Power system installation services', 'Installation', true),
('Industrial Automation', 'Automation solutions for manufacturing and industrial processes', 'Industrial automation services', 'Automation', true),
('Electrical Maintenance', 'Preventive and corrective maintenance for electrical systems', 'Electrical maintenance services', 'Maintenance', true),
('Safety & Compliance', 'Electrical safety audits and compliance consulting', 'Safety and compliance services', 'Safety', true)
ON CONFLICT DO NOTHING;

-- Sample Products
INSERT INTO public.products (name, description, category, price, stock_quantity, is_active) VALUES
('Industrial Circuit Breakers', 'High-quality circuit breakers for industrial applications', 'Safety Equipment', 1500.00, 50, true),
('Power Transformers', 'Step-up and step-down transformers for various applications', 'Transformers', 25000.00, 10, true),
('Control Panels', 'Custom-built electrical control panels', 'Control Systems', 5000.00, 25, true),
('Cable Management Systems', 'Professional cable management and routing solutions', 'Accessories', 200.00, 100, true),
('Electrical Meters', 'Digital and analog electrical measurement instruments', 'Instruments', 800.00, 75, true)
ON CONFLICT DO NOTHING;

-- Sample Testimonials
INSERT INTO public.testimonials (name, company, position, content, rating, is_featured, is_active) VALUES
('John Smith', 'ABC Manufacturing', 'Operations Manager', 'Nolads Engineering delivered exceptional electrical design services for our new facility. Professional, timely, and cost-effective.', 5, true, true),
('Sarah Johnson', 'XYZ Industries', 'Plant Manager', 'Their automation solutions increased our productivity by 30%. Highly recommended for industrial electrical work.', 5, true, true),
('Michael Brown', 'Tech Solutions Ltd', 'CEO', 'Outstanding electrical maintenance services. They keep our systems running smoothly with minimal downtime.', 4, false, true)
ON CONFLICT DO NOTHING;

-- Sample Blog Posts
INSERT INTO public.blog_posts (title, slug, content, excerpt, category, status, author_id, author_name, author_email, published_at) VALUES
('The Future of Industrial Automation', 'future-of-industrial-automation', 'Industrial automation is rapidly evolving with new technologies...', 'Exploring emerging trends in industrial automation and their impact on modern manufacturing.', 'Technology', 'published', 1, 'Nolads Engineering', 'engineering@nolads.com', NOW()),
('Electrical Safety Best Practices', 'electrical-safety-best-practices', 'Electrical safety is paramount in any industrial setting...', 'Essential safety guidelines and best practices for electrical work in industrial environments.', 'Safety', 'published', 1, 'Nolads Engineering', 'engineering@nolads.com', NOW()),
('Energy Efficiency in Modern Buildings', 'energy-efficiency-modern-buildings', 'Modern buildings require smart electrical systems...', 'How to implement energy-efficient electrical systems in commercial and industrial buildings.', 'Efficiency', 'published', 1, 'Nolads Engineering', 'engineering@nolads.com', NOW())
ON CONFLICT (slug) DO NOTHING;

-- Sample Blog Categories
INSERT INTO public.blog_categories (name, slug, description, is_active) VALUES
('Technology', 'technology', 'Latest technology trends and innovations', true),
('Safety', 'safety', 'Safety best practices and guidelines', true),
('Efficiency', 'efficiency', 'Energy efficiency and optimization tips', true),
('Power Systems', 'power-systems', 'Power systems design and management', true),
('Automation', 'automation', 'Industrial automation solutions', true)
ON CONFLICT (slug) DO NOTHING;

COMMENT ON TABLE public.users IS 'User profiles and authentication data';
COMMENT ON TABLE public.services IS 'Company services and offerings';
COMMENT ON TABLE public.products IS 'Products catalog and inventory';
COMMENT ON TABLE public.quotes IS 'Customer quote requests and proposals';
COMMENT ON TABLE public.contact_messages IS 'Contact form submissions and inquiries';
COMMENT ON TABLE public.testimonials IS 'Customer testimonials and reviews';
COMMENT ON TABLE public.images IS 'File uploads and image management';
COMMENT ON TABLE public.blog_posts IS 'Blog articles and content management';
COMMENT ON TABLE public.blog_categories IS 'Blog post categories and topics';
COMMENT ON TABLE public.blog_comments IS 'User comments on blog posts';

-- Storage bucket configuration
-- Create the 'images' storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'images',
  'images',
  true,
  10485760, -- 10MB limit
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml']
) ON CONFLICT (id) DO NOTHING;

-- Storage policies for images bucket (idempotent)
DROP POLICY IF EXISTS "Public can view images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload images" ON storage.objects;
DROP POLICY IF EXISTS "Users can update own images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can manage all images" ON storage.objects;

CREATE POLICY "Public can view images" ON storage.objects
FOR SELECT USING (bucket_id = 'images');

CREATE POLICY "Authenticated users can upload images" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'images'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Users can update own images" ON storage.objects
FOR UPDATE USING (
  bucket_id = 'images'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Users can delete own images" ON storage.objects
FOR DELETE USING (
  bucket_id = 'images'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Admins can manage all images" ON storage.objects
FOR ALL USING (
  bucket_id = 'images'
  AND auth.jwt() ->> 'role' = 'admin'
);
